In [7]:
# pd.read_csv() 使⽤預設參數
import pandas as pd
csv_url = "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.csv"
csv_df = pd.read_csv(csv_url)
csv_df
# pd.read_csv() ⾃⾏指定變數的名稱
import pandas as pd
csv_url = "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.csv"
csv_df = pd.read_csv(csv_url, header=None, skiprows=1, names=['number', 'player', 'pos', 'ht', 'wt', 'birth_date', 'college'])
csv_df

,number,player,pos,ht,wt,birth_date,college
0,0,Randy Brown,PG,6-2,190,"May 22, 1968","University of Houston, New Mexico State Univer..."
1,30,Jud Buechler,SF,6-6,220,"June 19, 1968",University of Arizona
2,35,Jason Caffey,PF,6-8,255,"June 12, 1973",University of Alabama
3,53,James Edwards,C,7-0,225,"November 22, 1955",University of Washington
4,54,Jack Haley,C,6-10,240,"January 27, 1964","University of California, Los Angeles"
5,9,Ron Harper,PG,6-6,185,"January 20, 1964",Miami University
6,23,Michael Jordan,SG,6-6,195,"February 17, 1963",University of North Carolina
7,25,Steve Kerr,PG,6-3,175,"September 27, 1965",University of Arizona
8,7,Toni Kukoc,SF,6-10,192,"September 18, 1968",NaN
9,13,Luc Longley,C,7-2,265,"January 19, 1969",University of New Mexico
10,33,Scottie Pippen,SF,6-8,210,"September 25, 1965",University of Central Arkansas
11,91,Dennis Rodman,PF,6-7,210,"May 13, 1961",Southeastern Oklahoma State University
12,22,John Salley,PF,6-11,230,"May 16, 1964",Georgia Institute of Technology
13,8,Dickey Simpkins,PF,6-9,248,"April 6, 1972",Providence College
14,34,Bill Wennington,C,7-0,245,"April 26, 1963",St. John's University

In [8]:
# pd.read_table() 指定 sep=";"
import pandas as pd
txt_url = "https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.txt"
txt_df = pd.read_table(txt_url, sep=";")
txt_df

,No.,Player,Pos,Ht,Wt,Birth Date,College
0,0,Randy Brown,PG,6-2,190,May 22; 1968,University of Houston; New Mexico State Univer...
1,30,Jud Buechler,SF,6-6,220,June 19; 1968,University of Arizona
2,35,Jason Caffey,PF,6-8,255,June 12; 1973,University of Alabama
3,53,James Edwards,C,7-0,225,November 22; 1955,University of Washington
4,54,Jack Haley,C,6-10,240,January 27; 1964,University of California; Los Angeles
5,9,Ron Harper,PG,6-6,185,January 20; 1964,Miami University
6,23,Michael Jordan,SG,6-6,195,February 17; 1963,University of North Carolina
7,25,Steve Kerr,PG,6-3,175,September 27; 1965,University of Arizona
8,7,Toni Kukoc,SF,6-10,192,September 18; 1968,NaN
9,13,Luc Longley,C,7-2,265,January 19; 1969,University of New Mexico
10,33,Scottie Pippen,SF,6-8,210,September 25; 1965,University of Central Arkansas
11,91,Dennis Rodman,PF,6-7,210,May 13; 1961,Southeastern Oklahoma State University
12,22,John Salley,PF,6-11,230,May 16; 1964,Georgia Institute of Technology
13,8,Dickey Simpkins,PF,6-9,248,April 6; 1972,Providence College
14,34,Bill Wennington,C,7-0,245,April 26; 1963,St. John's University

In [9]:
# pd.read_excel() 使⽤預設參數
import pandas as pd
xlsx_url = "https://storage.googleapis.com/ds_data_import/fav_nba_teams.xlsx"
chicsgo_bulls = pd.read_excel(xlsx_url)
chicsgo_bulls
# pd.read_excel() 指定⼯作表與讀取範圍
import pandas as pd
xlsx_url = "https://storage.googleapis.com/ds_data_import/fav_nba_teams.xlsx"
boston_celtics = pd.read_excel(xlsx_url, sheet_name='boston_celtics_2007_2008', skiprows=6, header=None, names=['number', 'player', 'pos'], usecols=[0, 1, 2])
boston_celtics

   number            player pos
0       5     Kevin Garnett  PF
1      50       Eddie House  PG
2      43  Kendrick Perkins   C
3      34       Paul Pierce  SF
4      66      Scot Pollard   C
5      41       James Posey  PF
6       0         Leon Powe   C
7      13       Gabe Pruitt  PG
8       9       Rajon Rondo  PG
9      44  Brian Scalabrine  PF

In [10]:
#JSON，檔案存在雲端
from requests import get
json_url = 'https://storage.googleapis.com/ds_data_import/chicago_bulls_1995_1996.json'
chicago_bulls_dict = get(json_url).json()
print(type(chicago_bulls_dict))
chicago_bulls_dict

<class 'dict'>

{'team_name': 'Chicago Bulls',
 'records': {'wins': 72, 'losses': 10},
 'coach': 'Phil Jackson',
 'assistant_coach': ['Jim Cleamons',
  'John Paxson',
  'Jimmy Rodgers',
  'Tex Winter'],
 'starting_lineups': {'PG': 'Ron Harper',
  'SG': 'Michael Jordan',
  'SF': 'Scottie Pippen',
  'PF': 'Dennis Rodman',
  'C': 'Luc Longley'}}

In [18]:
# JSON 檔案儲存在本機
#Load()將josn檔案匯入
from json import load
json_fp = "chicago_bulls_1995_1996 (1).json"
with open(json_fp) as f:
     chicago_bulls_dict = load(f)
print(type(chicago_bulls_dict))
chicago_bulls_dict

FileNotFoundError: [Errno 2] No such file or directory: 'chicago_bulls_1995_1996 (1).json'

In [19]:
winning_percentage = chicago_bulls_dict["records"]["wins"] / (chicago_bulls_dict["records"]["wins"] + chicago_bulls_dict["records"]["losses"])
fav_player = chicago_bulls_dict["starting_lineups"]["SG"]
print("勝率為 {:.2f}".format(winning_percentage))
print("最喜歡的球員是 {}".format(fav_player))

勝率為 0.88
最喜歡的球員是 Michael Jordan